# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
[tool.pytest.ini_options]
addopts = "-s -v -x --strict-markers -m 'not extra' --doctest-modules --cov=."


[tool.coverage.run]
branch = true
source = ["."]
omit = ["*_test.py", "*/test/*", "manage.py"]


[tool.coverage.report]
show_missing = true


[tool.black]
line-length = 120


[tool.flake8]
ignore = "E203,E266,H106,H904,E133"
max-line-length = 120
max-complexity = 25
hang-closing = true


[tool.pylint.'MESSAGES CONTROL']
disable = "R0903,R0913,R0901,W0613,W0718"


[tool.pylint.format]
max-line-length = "120"
