[tool.bandit]
exclude_dirs = ["venv", "django_project/tests", "django_project/storemgr/scripts", "*local_test*"]


[tool.black]
line-length = 120


[tool.coverage.report]
show_missing = true


[tool.coverage.run]
branch = true
omit = [
    "django_project/manage.py", 
    "django_project/core/asgi.py",
    "django_project/core/wsgi.py", 
    "django_project/*/local_test/*",
    "django_project/*/migrations/*",
    "django_project/*/scripts/*",
    ]
relative_files = true
source = ["django_project"]


[tool.isort]
profile = "black"


[tool.mypy]
exclude = ["venv/*", "local_test/*", "migrations/*"]
ignore_missing_imports = true


[tool.pytest.ini_options]
addopts = "-s -v -x --strict-markers -m 'not extra'"
testpaths = ["django_project/tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
]


[tool.ruff]
line-length = 120
exclude = ["django_project/manage.py", "django_project/tests", "django_project/storemgr/migrations", "django_project/*/scripts", "django_project/*/local_test"]
