# Generated by Django 4.1.7 on 2023-04-12 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=16, unique=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_id",
                    models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, unique=True),
                ),
                ("first_name", models.CharField(max_length=16)),
                ("last_name", models.CharField(max_length=16)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty", models.IntegerField(blank=True, default=1, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=16, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=16)),
                ("value", models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                "unique_together": {("key", "value")},
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, unique=True)),
                ("description", models.CharField(blank=True, max_length=128, null=True)),
                ("enabled", models.BooleanField(default=True)),
                ("attributes", models.ManyToManyField(blank=True, to="storemgr.productattribute")),
                ("brand", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="storemgr.brand")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_id",
                    models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, unique=True),
                ),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="storemgr.customer")),
                ("products", models.ManyToManyField(blank=True, through="storemgr.Invoice", to="storemgr.product")),
                ("status", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="storemgr.orderstatus")),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="order",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="storemgr.order"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="product",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="storemgr.product"
            ),
        ),
    ]
